/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.63
 * Generated at: 2022-09-07 01:25:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views._2Team;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class t2_005findex_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<head>\r\n");
      out.write("	<meta charset=\"UTF-8\">\r\n");
      out.write("	<title>Medirev</title>\r\n");
      out.write("	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no\">\r\n");
      out.write("	<link rel=\"icon\" href=\"favicon.png\" type=\"image/png\">\r\n");
      out.write("	<!-- Include Bootstrap CSS -->\r\n");
      out.write("	<link href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("	<!-- Include Font Awesome CSS -->\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css\">\r\n");
      out.write("	<!-- Include Font Awesome CSS -->\r\n");
      out.write("	<link href='https://fonts.googleapis.com/css?family=Oswald:400,700|Open+Sans:400,300,600,700,800' rel='stylesheet' type='text/css'>\r\n");
      out.write("	<!-- Include Medirev CSS -->\r\n");
      out.write("	<link href='resources/t2_css/style.css' rel='stylesheet' type='text/css'>\r\n");
      out.write("	<!-- SLIDER REVOLUTION 4.x CSS SETTINGS -->\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"css/settings.css\" media=\"screen\" />\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"resources/t2_css/t2_login.css\">\r\n");
      out.write("	<!-- Hospital MAIN CSS  -->\r\n");
      out.write("	<link href='resources/t2_css/hospital_main.css' rel='stylesheet' type='text/css'> \r\n");
      out.write("	<link href='resources/t2_css/hospital_detail.css' rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("	<link href='resources/t2_css/hospital_reserve.css' rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("	<link href='resources/t2_css/hospital_reserve_lookup.css' rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("	<script type=\"text/javascript\" src=\"resources/t2_js/jQuery.js\"></script>\r\n");
      out.write("	<!-- 주소 js -->\r\n");
      out.write("	<script src=\"//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("	<script type=\"text/javascript\" src=\"resources/t2_js/login_function.js\"></script>\r\n");
      out.write("	<!-- 로그인 JS -->\r\n");
      out.write("	<script type=\"text/javascript\" src=\"resources/t2_js/validCheck.js\"></script>\r\n");
      out.write("	<script type=\"text/javascript\" src=\"resources/t2_js/login_checkJS.js\"></script>\r\n");
      out.write("	<!-- board  -->\r\n");
      out.write("	<script type=\"text/javascript\" src=\"resources/t2_js/board.js\"></script>\r\n");
      out.write("	<script type=\"text/javascript\" src=\"resources/t2_js/board_comment.js\"></script>\r\n");
      out.write("	<link href='resources/t2_css/board.css' rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("	<!-- shop -->\r\n");
      out.write("	<script type=\"text/javascript\" src=\"resources/t2_js/shop_function.js\"></script>\r\n");
      out.write("	<link href='resources/t2_css/shopDetailPage.css' rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("	\r\n");
      out.write("	<!-- 로그인 내 정보페이지 -->\r\n");
      out.write("	<link href=\"resources/t2_css/t2_myPageCSS.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("	\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("			<nav class=\"index_nav\"><div class=\"index-nav-login\">");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, (java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginPage }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null), out, false);
      out.write("</div></nav>\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"container-fluid\">\r\n");
      out.write("				<div class=\"header-top\">\r\n");
      out.write("						<a href=\"team2Main\"><img class=\"index_logo_img\" src=\"resources/t2_img/logo.jpg\" alt=\"\" /></a>\r\n");
      out.write("					</div>\r\n");
      out.write("					\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("	<div id=\"indexMenu\">\r\n");
      out.write("        <ul>\r\n");
      out.write("            <li><a href=\"hospitalGo\">동물병원 찾기</a></li>\r\n");
      out.write("           <li class=\"t2-indexDropdown\">\r\n");
      out.write("           <a class=\"t2-indexDropbtn\">상품 판매</a>\r\n");
      out.write("           <ul class=\"t2-indexDropdown-content\">\r\n");
      out.write("            	<li><a href=\"viewProductPage.go?onExhibition=Y&pet_category=dog&toy_category=snack&toy=toy\">강아지</a></li>                     \r\n");
      out.write("            	<li><a href=\"viewProductPage.go?onExhibition=Y&pet_category=cat&toy_category=snack&toy=toy\">고양이</a></li>                 \r\n");
      out.write("            	<li><a href=\"viewProductPage.go?onExhibition=Y&pet_category=etc&toy_category=snack&toy=toy\">etc</a></li>                 \r\n");
      out.write("            </ul>\r\n");
      out.write("           </li>\r\n");
      out.write("            <li class=\"t2-indexDropdown\">\r\n");
      out.write("            	<a class=\"t2-indexDropbtn\">게시판</a>\r\n");
      out.write("            	<ul class=\"t2-indexDropdown-content\">\r\n");
      out.write("            	<li><a href=\"team2.boardlist?board_category=1\">강아지</a></li>                     \r\n");
      out.write("            	<li><a href=\"team2.boardlist?board_category=2\">고양이</a></li>                 \r\n");
      out.write("           		<li><a href=\"team2.boardlist?board_category=3\">etc</a></li>                 \r\n");
      out.write("            </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("</div>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, (java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contentPage }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null), out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	<section class=\"footer\">\r\n");
      out.write("		<div class=\"widget\">\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("				<div class=\"row\">\r\n");
      out.write("					<div class=\"col-md-3 col-md-offset-half col-sm-4 col-xs-12 single-widget\">\r\n");
      out.write("						<h2 class=\"widget-title\">HOSPITAL ADDRESS</h2>\r\n");
      out.write("						<div class=\"widget-inner\">\r\n");
      out.write("							<p>E44, Design Street, Web Corner Melbourne - 005</p>\r\n");
      out.write("							<ul>\r\n");
      out.write("								<li>Monday - Friday</li>\r\n");
      out.write("								<li>8.00 - 18.00</li>\r\n");
      out.write("								<li>Saturday</li>\r\n");
      out.write("								<li>8.00 - 18.00</li>\r\n");
      out.write("								<li>Sunday</li>\r\n");
      out.write("								<li>8.00 - 18.00</li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"col-md-3 col-md-offset-1  col-sm-4 col-xs-12 single-widget\">\r\n");
      out.write("						<h2 class=\"widget-title\">QUICK LINKS</h2>\r\n");
      out.write("						<div class=\"widget-inner\">\r\n");
      out.write("							<ul class=\"footer-menu\">\r\n");
      out.write("								<li><a href=\"\">Doctors</a></li>\r\n");
      out.write("								<li><a href=\"\">Services</a></li>\r\n");
      out.write("								<li><a href=\"\">Gallery</a></li>\r\n");
      out.write("								<li><a href=\"\">News</a></li>\r\n");
      out.write("								<li><a href=\"\">Terms of Use</a></li>\r\n");
      out.write("								<li><a href=\"\">Privacy Policy</a></li>\r\n");
      out.write("								<li><a href=\"\">Desclaimer</a></li>\r\n");
      out.write("								<li><a href=\"\">Sitemap</a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"col-md-3 col-md-offset-1  col-sm-4 col-xs-12 single-widget\">\r\n");
      out.write("						<h2 class=\"widget-title\">SIGNUP FOR NEWSLETTER</h2>\r\n");
      out.write("						<div class=\"widget-inner\">\r\n");
      out.write("							\r\n");
      out.write("							<div class=\"clearfix\"></div>\r\n");
      out.write("							<div class=\"social footer\">\r\n");
      out.write("								<a href=\"\"><i class=\"fa fa-twitter\"></i></a>\r\n");
      out.write("								<a href=\"\"><i class=\"fa fa-instagram\"></i></a>\r\n");
      out.write("								<a href=\"\"><i class=\"fa fa-google-plus\"></i></a>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"copyright text-center\">\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("				<div class=\"row\">\r\n");
      out.write("					<p class=\"copyright\">Shared by <i class=\"fa fa-love\"></i><a href=\"https://bootstrapthemes.co\">BootstrapThemes</a></p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("	<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js\"></script>\r\n");
      out.write("    <!-- Include all compiled plugins (below), or include individual files as needed -->\r\n");
      out.write("	<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js\"></script>\r\n");
      out.write("	<!-- SLIDER REVOLUTION 4.x SCRIPTS  -->\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jquery.themepunch.tools.min.js\"></script>   \r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jquery.themepunch.revolution.min.js\"></script>\r\n");
      out.write("	<!-- Waypoint -->\r\n");
      out.write("	<script src=\"http://cdnjs.cloudflare.com/ajax/libs/waypoints/2.0.3/waypoints.min.js\"></script>\r\n");
      out.write("	<script src=\"js/jquery.counterup.min.js\"></script>\r\n");
      out.write("	<!-- Include Medirev JavaScript -->\r\n");
      out.write("	<script src=\"js/script.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
