/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.63
 * Generated at: 2022-09-05 01:00:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views._2Team.t2login;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_005fbusiness_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/t2_css/t2_login.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://static.nid.naver.com/js/naverLogin_implicit-1.0.3.js\" charset=\"utf-8\"></script>\r\n");
      out.write("  <script type=\"text/javascript\" src=\"http://code.jquery.com/jquery-1.11.3.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"login_body\">\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"login_didididiv\">\r\n");
      out.write("	\r\n");
      out.write("	<ul class=\"menu__tabs\">\r\n");
      out.write("			<li><a  href=\"#item-1\"><i class=\"fa fa-user\"></i> 개인</a></li>\r\n");
      out.write("			<li><a class=\"active\" href=\"#item-2\"><i class=\"fa fa-building\"></i> 기업</a></li>	\r\n");
      out.write("		</ul>\r\n");
      out.write("		<section class=\"menu__wrapper\">\r\n");
      out.write("			<article id=\"item-1\" class=\"menu__item \">\r\n");
      out.write("				<h3>개인</h3>\r\n");
      out.write("				\r\n");
      out.write("				<form action=\"t2LoginDO\" method=\"post\" name=\"loginForm\" onsubmit=\"return logincheckCall()\">\r\n");
      out.write("\r\n");
      out.write("		<div class=\"login_txt\">\r\n");
      out.write("			<h2 class=\"login_h2\">Welcome!</h2>\r\n");
      out.write("			<div class=\"login-social\">\r\n");
      out.write("				<a href=\"\"><i class=\"fa fa-kakao\">kakao</i></a>\r\n");
      out.write("				<div id=\"naver_id_login\"></div>\r\n");
      out.write("				<a href=\"\"><i class=\"fa fa-google-plus\"></i></a>\r\n");
      out.write("							</div>\r\n");
      out.write("			\r\n");
      out.write("			<label class=\"login_label\"> <span>ID</span> \r\n");
      out.write("			<input class=\"login_input\" name=\"member_ID\" />\r\n");
      out.write("			</label> <label class=\"login_label\"> <span>Password</span> \r\n");
      out.write("			<input class=\"login_input1\" name=\"member_PW\" />\r\n");
      out.write("			</label>\r\n");
      out.write("			<span class=\"pw_alert\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${r}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("			<input type=\"checkbox\" id=\"login_idSave\">아이디 기억하기\r\n");
      out.write("			<p class=\"forgot-pass\" type=\"button\"  style=\"font-size: 12px;\" onclick=\"location.href='acceptgo?member=1' \">회원가입</p>\r\n");
      out.write("			<p class=\"forgot-pass\"  style=\"font-size: 12px;\" onclick=\"location.href='t2FindID.go'\">아이디를 잊으셨나요?</p>\r\n");
      out.write("			<p class=\"forgot-pass\"  style=\"font-size: 12px;\" onclick=\"location.href='t2FindPW.go'\">비밀번호를 잊으셨나요?</p>\r\n");
      out.write("			<div class=\"box bg-1\">\r\n");
      out.write("			<input type=\"submit\" class=\"login-btn\" value=\"L o g i n\"/>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("			</article>\r\n");
      out.write("			\r\n");
      out.write("			<article id=\"item-2\" class=\"menu__item item-active\">\r\n");
      out.write("				<h3>기업</h3>\r\n");
      out.write("			<form action=\"t2LoginDO.business\" method=\"post\" name=\"loginFormBusiness\" onsubmit=\"return loginCheck_business()\">\r\n");
      out.write("\r\n");
      out.write("		<div class=\"login_txt\">\r\n");
      out.write("			<h2 class=\"login_h2\">Welcome!</h2>\r\n");
      out.write("			\r\n");
      out.write("			<label class=\"login_label\"> <span>ID</span> \r\n");
      out.write("			<input class=\"login_input3\" name=\"vet_ID\" />\r\n");
      out.write("			</label> <label class=\"login_label\"> <span>Password</span> \r\n");
      out.write("			<input class=\"login_input1\" name=\"vet_PW\" />\r\n");
      out.write("			</label>\r\n");
      out.write("			<span class=\"pw_alert\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rb}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("			<input type=\"checkbox\" id=\"login_idSave1\">아이디 기억하기\r\n");
      out.write("			<p class=\"forgot-pass\"  style=\"font-size: 12px;\" onclick=\"location.href='acceptgo?member=2' \">회원가입</p>\r\n");
      out.write("			<p class=\"forgot-pass\"  style=\"font-size: 12px;\" onclick=\"location.href='businessIDFind.go'\">아이디를 잊으셨나요?</p>\r\n");
      out.write("			<p class=\"forgot-pass\"  style=\"font-size: 12px;\" onclick=\"location.href='businessPWFind.go'\">비밀번호를 잊으셨나요?</p>\r\n");
      out.write("			<div class=\"box bg-1\">\r\n");
      out.write("			<input type=\"submit\" class=\"login-btn\" value=\"L o g i n\"/>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("</form>\r\n");
      out.write("			</article>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		</section>\r\n");
      out.write("		\r\n");
      out.write("	\r\n");
      out.write("</div>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("  	var naver_id_login = new naver_id_login(\"BuwruEVQIqPoVW9Sc3Uo\", \"http://localhost/main/naver.login\");\r\n");
      out.write("  	var state = naver_id_login.getUniqState();\r\n");
      out.write("  	naver_id_login.setButton(\"white\", 2,40);\r\n");
      out.write("  	naver_id_login.setDomain(\"http://localhost/main/naver.login\");\r\n");
      out.write("  	naver_id_login.setState(state);\r\n");
      out.write("  	naver_id_login.setPopup();\r\n");
      out.write("  	naver_id_login.init_naver_id_login();\r\n");
      out.write("  </script>\r\n");
      out.write("</body>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(function() {\r\n");
      out.write("\r\n");
      out.write("	// Menu Tabular\r\n");
      out.write("	var $menu_tabs = $('.menu__tabs li a'); \r\n");
      out.write("	$menu_tabs.on('click', function(e) {\r\n");
      out.write("		e.preventDefault();\r\n");
      out.write("		$menu_tabs.removeClass('active');\r\n");
      out.write("		$(this).addClass('active');\r\n");
      out.write("\r\n");
      out.write("		$('.menu__item').fadeOut(300);\r\n");
      out.write("		$(this.hash).delay(300).fadeIn();\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("});</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
