/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.63
 * Generated at: 2022-09-06 05:54:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views._2Team.t2login;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class petRegistration_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"t2-join-outdiv\">\r\n");
      out.write("<form action=\"petInformationReg.do\" method=\"POST\" class=\"joinForm\" enctype=\"multipart/form-data\" name=\"petReg\" onsubmit=\"return petRegDO()\"> \r\n");
      out.write("                                                                                               \r\n");
      out.write("      <h2>펫 등록하기</h2>\r\n");
      out.write("      <h6>대표 한마리만 등록이 가능합니다</h6>\r\n");
      out.write("      <div class=\"join-textForm brith\" style=\"text-align: center;\">   \r\n");
      out.write("        <img id=\"image\" style=\"width: 100px;height: 100px; display: none; border-radius: 50%;\">\r\n");
      out.write("        <input name=\"baby_img\" type=\"file\" class=\"join-name\" id=\"baby_img\" style=\"padding-bottom: 30px;\"> \r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("      <div class=\"join-textForm\">   \r\n");
      out.write("        <input name=\"baby_name\" type=\"text\" class=\"join-name\" placeholder=\"펫이름\" id=\"babyName\">      \r\n");
      out.write("        <span id=\"idcheckResult\"></span>\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      <div class=\"join-textForm brith\">\r\n");
      out.write("        <input name=\"baby_weight\"  class=\"join-name\" placeholder=\"몸무게\" style=\"width: 80px;\" id=\"babyWeight\">kg\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("      <div class=\"join-textForm brith\">\r\n");
      out.write("      	생일&nbsp;&nbsp;<input name=\"baby_birth\" type=\"date\" class=\"join-birth\" id=\"babyBirth\">\r\n");
      out.write("      </div> \r\n");
      out.write("      \r\n");
      out.write("      <div class=\"join-textForm brith\">\r\n");
      out.write("      	성별 &nbsp;&nbsp;\r\n");
      out.write("        <input name=\"baby_sex\" type=\"radio\" class=\"join-sex\" value=\"m\" checked=\"checked\">남아\r\n");
      out.write("        &nbsp;&nbsp;<input name=\"baby_sex\" type=\"radio\" class=\"join-sex\" value=\"w\">여아\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("      <div class=\"join-textForm brith\">\r\n");
      out.write("      	종류 &nbsp;&nbsp;\r\n");
      out.write("        <input name=\"baby_type\" type=\"radio\" class=\"join-sex\" value=\"dog\" checked=\"checked\">강아지\r\n");
      out.write("        &nbsp;&nbsp;<input name=\"baby_type\" type=\"radio\" class=\"join-sex\" value=\"cat\">고양이\r\n");
      out.write("        &nbsp;&nbsp;<input name=\"baby_type\" type=\"radio\" class=\"join-sex\" value=\"etc\">그 외\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("      <div class=\"join-textForm brith\">\r\n");
      out.write("      	품종 &nbsp;&nbsp;\r\n");
      out.write("        <input name=\"baby_typeDetail\" class=\"join-cellphoneNo\" placeholder=\"품종\" style=\"width: 250px;\" id=\"babyDetail\">\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("       <div class=\"join-textForm brith\">\r\n");
      out.write("      	중성화 &nbsp;&nbsp;\r\n");
      out.write("        <input name=\"baby_neut\" type=\"radio\" class=\"join-sex\" value=\"yes\" checked=\"checked\">함\r\n");
      out.write("        &nbsp;&nbsp;<input name=\"baby_neut\" type=\"radio\" class=\"join-sex\" value=\"no\">안함\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("      <input type=\"hidden\" name=\"baby_memberID\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginMember.member_ID }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("      \r\n");
      out.write("      <input type=\"submit\" class=\"join-btn\" value=\"등 록\"/>\r\n");
      out.write("    </form>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("document.getElementById(\"baby_img\").onchange = function () {\r\n");
      out.write("    var reader = new FileReader();\r\n");
      out.write("    $('#image').css({ 'display' : '' });\r\n");
      out.write("    reader.onload = function (e) {\r\n");
      out.write("        // get loaded data and render thumbnail.\r\n");
      out.write("        \r\n");
      out.write("        document.getElementById(\"image\").src = e.target.result;\r\n");
      out.write("    };\r\n");
      out.write("\r\n");
      out.write("    // read the image file as a data URL.\r\n");
      out.write("    reader.readAsDataURL(this.files[0]);\r\n");
      out.write("};\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
