/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.64
 * Generated at: 2022-09-07 11:08:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views._1Team.master;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class purchasePage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/Users/mitakeran/Team1FinalProject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/FinalProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1661307823390L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("<link href='resources/t2_css/purchasedPage.css' rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("<script type=\"text/javascript\" src=\"resources/js/purchasePage.js\"></script>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("$(function(){\n");
      out.write("	\n");
      out.write("	var ProductPrice = document.getElementById(\"ProductPrice\").value;\n");
      out.write("	var quantity = document.getElementById(\"quantity\").value;\n");
      out.write("	\n");
      out.write("	$('#price').text(ProductPrice * quantity);\n");
      out.write("	$('#subPrice').text(ProductPrice * quantity);\n");
      out.write("	$('#totalPrice').text(ProductPrice * quantity + 3000);\n");
      out.write("	\n");
      out.write("	\n");
      out.write("	\n");
      out.write("	\n");
      out.write("	\n");
      out.write(" $('#sameAddressControl').click(function(){\n");
      out.write("	 console.log(\"asdasd\");\n");
      out.write("     $(\"#addrSearchBtn\").css(\"display\",\"inline\");\n");
      out.write("     var same = this.checked;\n");
      out.write("     $('#billAddress').val(same ? $('#shipAddress').text():'');\n");
      out.write("     $('#billCity').val(same ? $('#shipCity').text():'');\n");
      out.write("     $('#billState').val(same ? $('#shipState').text():'');\n");
      out.write("     $('#billState1').val(same ? $('#shipState1').text():'');\n");
      out.write("     $('#billState2').val(same ? $('#shipState2').text():'');\n");
      out.write("     $('#billZip').val(same ? $('#shipZip').val():'');\n");
      out.write("          if(same == true){\n");
      out.write("              $('#billingAddress input').filter('input:text')\n");
      out.write("             	 .attr('readonly',true)\n");
      out.write("             	 .css('opacity', 0.5);\n");
      out.write("             $(\"#addrSearchBtn\").css(\"display\",\"none\");\n");
      out.write("             	}else{\n");
      out.write("              $('#billingAddress input').filter('input:text').attr('readonly',false)\n");
      out.write("           	 .css('opacity', 1);\n");
      out.write("          }\n");
      out.write("   });\n");
      out.write(" \n");
      out.write(" $('#payment').click(function(){\n");
      out.write("	 	var totalPrice = $('#totalPrice').text();\n");
      out.write("		$.ajax({\n");
      out.write("		url:'team1_kakaopay',\n");
      out.write("		type : \"POST\",\n");
      out.write("		dataType:'json',\n");
      out.write("		data :	{\"totalPrice\" : totalPrice},\n");
      out.write("		success:function(data){\n");
      out.write("			var box = data.next_redirect_pc_url;\n");
      out.write("			var kakaoPop= window.open(box,'kakaoPay','width=500, height=800');\n");
      out.write("			{\n");
      out.write("				\n");
      out.write("			}\n");
      out.write("		},\n");
      out.write("		error:function(error){\n");
      out.write("			alert(\"실패\");\n");
      out.write("		}\n");
      out.write("	});\n");
      out.write("});\n");
      out.write("\n");
      out.write("	\n");
      out.write("}); \n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("function UpdateANDINsert() {\n");
      out.write("	\n");
      out.write("	var totalPrice = $('#totalPrice').text(); // 총금액\n");
      out.write("	alert(\"총금액 : \" + totalPrice);\n");
      out.write("	\n");
      out.write("	 var shipAddress = $('#shipAddress').text();	// 회원 정보\n");
      out.write("	alert(\"주문자ID : \" + shipAddress);\n");
      out.write("	 \n");
      out.write("	var Recipient = document.getElementById(\"billAddress\").value;  // 받는사람\n");
      out.write("	alert(\"수령인 : \" + Recipient);\n");
      out.write("	\n");
      out.write("	/* \n");
      out.write("	var phoneNum = document.getElementById(\"billCity\").value; // 받는사람 전화번호\n");
      out.write("	alert(\"수령인 전화번호 : \" + phoneNum);\n");
      out.write("	\n");
      out.write("	var billState = document.getElementById(\"billState\").value; // 우편번호\n");
      out.write("	alert(\"수령인 우편번호 : \" + billState);\n");
      out.write("	\n");
      out.write("	var billState1 = document.getElementById(\"billState1\").value; // 도로명주소\n");
      out.write("	alert(\"수령인 도로명주소 : \" + billState1);\n");
      out.write("	\n");
      out.write("	var billState2 = document.getElementById(\"billState2\").value; // 상세주소\n");
      out.write("	alert(\"수령인 상세주소 : \" + billState2);\n");
      out.write("	  */\n");
      out.write("	/* var memo = document.getElementById(\"billZip\").value; // 메모\n");
      out.write("	alert(\"메모 : \" + billZip);\n");
      out.write("	 */\n");
      out.write("	 \n");
      out.write("	/*  var p_name = document.getElementsById(\"p_name\"); // 상품이름\n");
      out.write("	alert(\"상품이름 : \" + p_name);\n");
      out.write("	\n");
      out.write("	var qt = document.getElementsById(\"qt\"); // 수량\n");
      out.write("	alert(\"상품수량 : \" + qt);\n");
      out.write("	\n");
      out.write("	var ProductPrice = document.getElementsById(\"ProductPrice\"); // 상품 금액\n");
      out.write("	alert(\"상품금액 : \" + ProductPrice); */\n");
      out.write("	 \n");
      out.write("	\n");
      out.write("				 \n");
      out.write("	\n");
      out.write("/* 	var = \n");
      out.write("	\n");
      out.write("	\n");
      out.write("	location.href='UpdateANDINsert'; */\n");
      out.write("	\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	\n");
      out.write("<fieldset>\n");
      out.write("      <div style=\" margin-bottom: 20px;border: 3px solid #000000;\">\n");
      out.write("      	<div>Order / Payment</div>\n");
      out.write("      </div>\n");
      out.write("      <div style=\" margin-top: 20px;border: 3px solid #000000;\">\n");
      out.write("      	<div>회원 정보</div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"divTable minimalistBlack\" id=\"shippingAddress\">\n");
      out.write("      	<div class=\"divTableHeading\">\n");
      out.write("    		<div class=\"divTableRow\">\n");
      out.write("    		<div class=\"divTableHead\">Recipient Info</div>\n");
      out.write("    		<div class=\"divTableHead\">주문자 정보</div>\n");
      out.write("    		</div>\n");
      out.write("  		</div>\n");
      out.write("  		<div class=\"divTableBody\">\n");
      out.write("    		<div class=\"divTableRow\">\n");
      out.write("      			<div class=\"divTableCell\">주문자</div>\n");
      out.write("      			<div class=\"divTableCell\"><span name=\"shipAddress\" id=\"shipAddress\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginMember.member_ID }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span></div>\n");
      out.write("      		</div>\n");
      out.write("    		<div class=\"divTableRow\">\n");
      out.write("      			<div class=\"divTableCell\">휴대전화</div>\n");
      out.write("      			<div class=\"divTableCell\"><span name=\"shipCity\" id=\"shipCity\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginMember.member_phoneNum }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span></div>\n");
      out.write("    		</div>\n");
      out.write("    		<div class=\"divTableRow\">\n");
      out.write("      			<div class=\"divTableCell\">주소</div>\n");
      out.write("      			<div class=\"divTableCell\"><span name=\"shipState\" id=\"shipState\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${addr[2]}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\n");
      out.write("      									  <span name=\"shipState1\" id=\"shipState1\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${addr[0]}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\n");
      out.write("      									  <span name=\"shipState2\" id=\"shipState2\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${addr[1]}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\n");
      out.write("      									</div>\n");
      out.write("    		</div>\n");
      out.write("    		<div class=\"divTableRow\">\n");
      out.write("      			<div class=\"divTableCell\">배송 시 메모</div>\n");
      out.write("      			<div class=\"divTableCell\"> <input type=\"text\" name=\"shipZip\" id=\"shipZip\" value=\"빠른 배송 부탁드립니다.\"\"/></div>\n");
      out.write("    		</div>\n");
      out.write("  	</div>\n");
      out.write("	</div>\n");
      out.write("	\n");
      out.write("	\n");
      out.write("	<div style=\" margin-top: 20px;border: 3px solid #000000;\">\n");
      out.write("      	<div>배송 정보\n");
      out.write("      	<input type=\"checkbox\" id=\"sameAddressControl\"/>회원정보와 동일합니다.</div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"divTable minimalistBlack\" id=\"billingAddress\">\n");
      out.write("      \n");
      out.write("      	<div class=\"divTableHeading\">\n");
      out.write("    		<div class=\"divTableRow\">\n");
      out.write("    		<div class=\"divTableHead\">Orderer Info</div>\n");
      out.write("    		<div class=\"divTableHead\">주문자 정보</div>\n");
      out.write("    		</div>\n");
      out.write("  		</div>\n");
      out.write("  		<div class=\"divTableBody\">\n");
      out.write("    		<div class=\"divTableRow\">\n");
      out.write("      			<div class=\"divTableCell\">수령인</div>\n");
      out.write("      			<div class=\"divTableCell\"><input type=\"text\" name=\"billAddress\" id=\"billAddress\"/></div>\n");
      out.write("      		</div>\n");
      out.write("    		<div class=\"divTableRow\">\n");
      out.write("      			<div class=\"divTableCell\">휴대전화</div>\n");
      out.write("      			<div class=\"divTableCell\"><input type=\"text\" name=\"billCity\" id=\"billCity\"/></div>\n");
      out.write("    		</div>\n");
      out.write("    		<div class=\"divTableRow\">\n");
      out.write("      			<div class=\"divTableCell\">배송지 주소</div>\n");
      out.write("      			<div class=\"divTableCell\"><input type=\"text\" name=\"billState\" id=\"billState\" class=\"billState\" placeholder=\"우편번호\"  style=\"width: 200px;\"/>\n");
      out.write("      									  <input type=\"text\" name=\"billState1\" id=\"billState1\" placeholder=\"도로명주소\" style=\"width: 200px;\"/>\n");
      out.write("      									  <input type=\"text\" name=\"billState2\" id=\"billState2\" placeholder=\"상세주소\" style=\"width: 200px;\"/>\n");
      out.write("      									  <span id=\"addrSearchBtn\" style=\"display:inline;\">[검색]</span></div>\n");
      out.write("    		</div>\n");
      out.write("    		<div class=\"divTableRow\">\n");
      out.write("      			<div class=\"divTableCell\">배송 시 메모</div>\n");
      out.write("      			<div class=\"divTableCell\"><input type=\"text\" name=\"billZip\" id=\"billZip\" placeholder=\"빠른 배송 부탁드립니다.\"/></div>\n");
      out.write("    		</div>\n");
      out.write("    		\n");
      out.write("    	\n");
      out.write("  	</div>\n");
      out.write("  	\n");
      out.write("  	</div>\n");
      out.write("      <div style=\" margin-top: 20px;border: 3px solid #000000;\">\n");
      out.write("      	<div>상품 정보</div>\n");
      out.write("      </div>\n");
      out.write("      \n");
      out.write("      <div class=\"divTable minimalistBlack\">\n");
      out.write("      	<div class=\"container\">\n");
      out.write("\n");
      out.write("		<section id=\"cart\" class=\"cart\">  \n");
      out.write("		\n");
      out.write("		<div  id=\"product\" class=\"product\">\n");
      out.write("			<article>\n");
      out.write("				<header>\n");
      out.write("						<img src=\"resources/reviewFile/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.product_thumnail }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("				</header>\n");
      out.write("				<div>\n");
      out.write("    			<input type=\"hidden\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginMember.member_ID }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" id=\"Order_User_ID\">\n");
      out.write("    			<input type=\"hidden\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.product_num }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" id=\"Order_ProductNum\">\n");
      out.write("    			<input type=\"hidden\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.product_price * param.quantity + 3000}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" id=\"Order_TotalPrice\">\n");
      out.write("    			<input type=\"hidden\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.product_thumnail }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" id=\"Order_thumbnail\">\n");
      out.write("    		</div>\n");
      out.write("				<div class=\"content\">\n");
      out.write("					<span class=\"p_name\" id=\"p_name\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.product_title }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\n");
      out.write("				</div>\n");
      out.write("				<footer class=\"content\">\n");
      out.write("				<input id=\"ProductPrice\" type=\"hidden\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.product_price }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("				<input id=\"quantity\" type=\"hidden\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.quantity }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("					<span class=\"qt-minus\" id=\"qt\">수량 : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.quantity }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\n");
      out.write("					<span class=\"price\" id=\"price\" ></span>\n");
      out.write("					<span class=\"onePriceWon\">가격 : </span>\n");
      out.write("				</footer>\n");
      out.write("			</article>\n");
      out.write("			</div>\n");
      out.write("\n");
      out.write("		</section>\n");
      out.write("\n");
      out.write("	</div>\n");
      out.write("</div>\n");
      out.write("</fieldset>\n");
      out.write("	\n");
      out.write("\n");
      out.write("	<footer id=\"site-footer\">\n");
      out.write("		<div class=\"container clearfix\">\n");
      out.write("\n");
      out.write("			<div class=\"left\">\n");
      out.write("				<h1 class=\"subtotal\"><span id=\"subPrice\"></span>원</h1>\n");
      out.write("				<h3 class=\"tax\">배송비 : <span>3000</span>원</h3>\n");
      out.write("			</div>\n");
      out.write("\n");
      out.write("			<div class=\"right\">\n");
      out.write("				<h1 class=\"total\"><span id=\"totalPrice\"></span>원</h1>\n");
      out.write("				<a class=\"payment\" id=\"payment\">Payment</a>\n");
      out.write("			</div>\n");
      out.write("\n");
      out.write("		</div>\n");
      out.write("	</footer>\n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\n");
      out.write("function orderInsert(){\n");
      out.write("	\n");
      out.write("	\n");
      out.write("	var Order_User_ID = document.getElementById(\"Order_User_ID\").value; // 주문자\n");
      out.write("	var phoneNum = document.getElementById(\"billCity\").value; // 폰넘버\n");
      out.write("	var quantity = document.getElementById(\"quantity\").value; // 수량\n");
      out.write("	var Order_ProductNum = document.getElementById(\"Order_ProductNum\").value; // 수량\n");
      out.write("	var billState = document.getElementById(\"billState\").value; // 우편번호\n");
      out.write("	var billState1 = document.getElementById(\"billState1\").value; // 도로명주소\n");
      out.write("	var billState2 = document.getElementById(\"billState2\").value; // 상세주소\n");
      out.write("	\n");
      out.write("	var ProductPrice = document.getElementById(\"ProductPrice\").value; // 상품1개 가격\n");
      out.write("	var Order_TotalPrice = document.getElementById(\"Order_TotalPrice\").value; // 상품1개 가격\n");
      out.write("	var memo = document.getElementById(\"billZip\").value; // 메모\n");
      out.write("	var Recipient = document.getElementById(\"billAddress\").value; // 수령인\n");
      out.write("	var Order_thumbnail = document.getElementById(\"Order_thumbnail\").value; // 메모\n");
      out.write("	\n");
      out.write("	\n");
      out.write("	\n");
      out.write("	location.href='orderInsert.do?Order_User_ID=' + Order_User_ID +\n");
      out.write("			'&Order_ProductNum=' + Order_ProductNum +\n");
      out.write("			'&Order_PhoneNumber=' + phoneNum +\n");
      out.write("			'&Product_Quantity=' + quantity +\n");
      out.write("			'&billState=' + billState +\n");
      out.write("			'&billState1=' + billState1 +\n");
      out.write("			'&billState2=' + billState2 +\n");
      out.write("			'&Product_Price=' + ProductPrice +\n");
      out.write("			'&Order_TotalPrice=' + Order_TotalPrice +\n");
      out.write("			'&Shipping_Memo=' + memo +\n");
      out.write("			'&Recipient=' + Recipient +\n");
      out.write("			'&Order_thumbnail=' + Order_thumbnail;\n");
      out.write("	};\n");
      out.write("\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
