/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.64
 * Generated at: 2022-09-07 11:01:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views._1Team.master;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class team1ShopForDog_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

private static org.apache.jasper.runtime.ProtectedFunctionMapper _jspx_fnmap_0;

static {
  _jspx_fnmap_0= org.apache.jasper.runtime.ProtectedFunctionMapper.getInstance();
  _jspx_fnmap_0.mapFunction("fn:length", org.apache.taglibs.standard.functions.Functions.class, "length", new Class[] {java.lang.Object.class});
  _jspx_fnmap_0.mapFunction("fn:substring", org.apache.taglibs.standard.functions.Functions.class, "substring", new Class[] {java.lang.String.class, int.class, int.class});
}

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/Users/mitakeran/Team1FinalProject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/FinalProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/Users/mitakeran/Team1FinalProject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/FinalProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1661307823390L));
    _jspx_dependants.put("jar:file:/Users/mitakeran/Team1FinalProject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/FinalProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\n");
      out.write("$(function() {\n");
      out.write("\n");
      out.write("	// Menu Tabular\n");
      out.write("	var $menu_tabs = $('.menu__tabs li a'); \n");
      out.write("	$menu_tabs.on('click', function(e) {\n");
      out.write("		e.preventDefault();\n");
      out.write("		$menu_tabs.removeClass('active');\n");
      out.write("		$(this).addClass('active');\n");
      out.write("\n");
      out.write("		$('.menu__item').fadeOut(300);\n");
      out.write("		$(this.hash).delay(300).fadeIn();\n");
      out.write("	});\n");
      out.write("\n");
      out.write("});\n");
      out.write("\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("<style type=\"text/css\">\n");
      out.write("html {\n");
      out.write("	-webkit-box-sizing: border-box;\n");
      out.write("	-moz-box-sizing: border-box;\n");
      out.write("	box-sizing: border-box;\n");
      out.write("}\n");
      out.write("\n");
      out.write("*, \n");
      out.write("*:before, \n");
      out.write("*:after {\n");
      out.write("	/* margin: 0; */\n");
      out.write("	padding: 0;\n");
      out.write("	-webkit-box-sizing: inherit;\n");
      out.write("	-moz-box-sizing: inherit;\n");
      out.write("	box-sizing: inherit;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/*--------------------------\n");
      out.write("* MENU TABS\n");
      out.write("---------------------------*/\n");
      out.write(".menu__tabs {\n");
      out.write("	list-style: none;\n");
      out.write("	overflow: hidden;\n");
      out.write("	margin-left: 10%;\n");
      out.write("}\n");
      out.write(".menu__tabs li {\n");
      out.write("	float: left;\n");
      out.write("	margin-right: 2px;\n");
      out.write("	font-size: 1.3em;\n");
      out.write("}\n");
      out.write(".menu__tabs a {\n");
      out.write("	padding: 1em;\n");
      out.write("	background: #333b48;\n");
      out.write("	display: inline-block;\n");
      out.write("	color: #FFF;\n");
      out.write("	text-decoration: none;\n");
      out.write("	-webkit-border-radius: 4px 4px 0 0;\n");
      out.write("	-moz-border-radius: 4px 4px 0 0;\n");
      out.write("	border-radius: 4px 4px 0 0;\n");
      out.write("	-webkit-transition: all 0.3s ease;\n");
      out.write("	-o-transition: all 0.3s ease;\n");
      out.write("	transition: all 0.3s ease;\n");
      out.write("	-webkit-box-shadow: inset 0 -2px 5px rgba(0,0,0,0.2);\n");
      out.write("	-moz-box-shadow: inset 0 -2px 5px rgba(0,0,0,0.2);\n");
      out.write("	box-shadow: inset 0 -2px 5px rgba(0,0,0,0.2);\n");
      out.write("}\n");
      out.write(".menu__tabs a:hover {\n");
      out.write("	background: #515a68;\n");
      out.write("}\n");
      out.write(".menu__tabs a.active {\n");
      out.write("	color: #333b48;\n");
      out.write("	background: #FFF;\n");
      out.write("	-webkit-box-shadow: none;\n");
      out.write("	-moz-box-shadow: none;\n");
      out.write("	box-shadow: none;\n");
      out.write("}\n");
      out.write(".menu__tabs a.active i {color: #80cbb7;}\n");
      out.write(".menu__tabs a i {\n");
      out.write("	margin-right: 3px;\n");
      out.write("	color: #aaaaaa;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/*--------------------------\n");
      out.write("* MENU WRAPPER\n");
      out.write("---------------------------*/\n");
      out.write(".menu {\n");
      out.write("	margin: 55px auto;\n");
      out.write("	width: 80%;\n");
      out.write("	max-width: 600px;\n");
      out.write("	position: relative;\n");
      out.write("}\n");
      out.write(".menu__wrapper {\n");
      out.write("	padding: 2em;\n");
      out.write("	position: relative;\n");
      out.write("	z-index: 400;\n");
      out.write("	/* background: #FFF; */\n");
      out.write("	min-height: 300px;\n");
      out.write("	-webkit-border-radius: 0 4px 4px 4px;\n");
      out.write("	-moz-border-radius: 0 4px 4px 4px;\n");
      out.write("	border-radius: 0 4px 4px 4px;\n");
      out.write("}\n");
      out.write(".menu--shadow {\n");
      out.write("	position: absolute;\n");
      out.write("	z-index: 300;\n");
      out.write("	bottom: -5px;\n");
      out.write("	height: 25px;\n");
      out.write("	width: 100%;\n");
      out.write("}\n");
      out.write(".menu--shadow:after,\n");
      out.write(".menu--shadow:before {\n");
      out.write("	content: '';\n");
      out.write("	display: block;\n");
      out.write("	width: 50%;\n");
      out.write("	height: 25px;\n");
      out.write("	position: absolute;\n");
      out.write("	left: 0;\n");
      out.write("	background: rgba(0,0,0,0.2);\n");
      out.write("	-webkit-border-radius: 25px;\n");
      out.write("	-moz-border-radius: 25px;\n");
      out.write("	border-radius: 25px;\n");
      out.write("	-webkit-box-shadow: 0 0 15px 5px rgba(0,0,0,0.25);\n");
      out.write("	-moz-box-shadow: 0 0 15px 5px rgba(0,0,0,0.25);\n");
      out.write("	box-shadow: 0 0 15px 5px rgba(0,0,0,0.25);\n");
      out.write("	-webkit-transform: scale(0.8) rotate(-4deg);\n");
      out.write("	-ms-transform: scale(0.8) rotate(-4deg);\n");
      out.write("	-o-transform: scale(0.8) rotate(-4deg);\n");
      out.write("	transform: scale(0.8) rotate(-4deg);\n");
      out.write("}\n");
      out.write(".menu--shadow:after {\n");
      out.write("	right: 0;\n");
      out.write("	left: auto;\n");
      out.write("	-webkit-transform: scale(0.8) rotate(4deg);\n");
      out.write("	-ms-transform: scale(0.8) rotate(4deg);\n");
      out.write("	-o-transform: scale(0.8) rotate(4deg);\n");
      out.write("	transform: scale(0.8) rotate(4deg);\n");
      out.write("}\n");
      out.write(".menu__wrapper .menu__item {\n");
      out.write("	line-height: 1.3;\n");
      out.write("	color: #76716f;\n");
      out.write("	display: none;\n");
      out.write("}\n");
      out.write(".menu__wrapper .menu__item.item-active {\n");
      out.write("	display: block;\n");
      out.write("}\n");
      out.write(".menu__wrapper .menu__item h3 {\n");
      out.write("	font-size: 1.8em;\n");
      out.write("	color: #333b48;\n");
      out.write("	border-bottom: 1px solid #d9d9d9;\n");
      out.write("	padding-bottom: 5px;\n");
      out.write("	margin-bottom: 12px;\n");
      out.write("}\n");
      out.write(".menu__wrapper .menu__item p {\n");
      out.write("	/* font-size: 1.3em;\n");
      out.write("	line-height: 1.6em;\n");
      out.write("	color: #76716f; */\n");
      out.write("}\n");
      out.write("\n");
      out.write("</style>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- <script type=\"text/javascript\">\n");
      out.write("/* 상품 디테일 페이지로 이동 */\n");
      out.write("	function gotoDetail(num) {\n");
      out.write("			location.href=\"enter.productDetail\"?num_PK=\"+num;\n");
      out.write("		}\n");
      out.write("/* 상품 카테고리별 출력 */\n");
      out.write(" 		function selectACategory() {\n");
      out.write("			var categoryNum = document.getElementById('categoryNumSelect');\n");
      out.write("			var cv = categoryNum.options[categoryNum.selectedIndex].value;\n");
      out.write("			location.href=\"get.team1byCategory?categoryNum=\"+cv;\n");
      out.write("		};		\n");
      out.write("</script> -->\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write(" <div class=\"store_wrap\">   \n");
      out.write("        <div class=\"store_header\">\n");
      out.write("            <div class=\"store_for_dog\">\n");
      out.write("                <img class=\"store_for_dog_img\" src=\"resources/img/about3.png\" alt=\"\">\n");
      out.write("            </div>\n");
      out.write("            <h2>\n");
      out.write("                <a href=\"#\">FOR DOG</a>\n");
      out.write("            </h2>\n");
      out.write("        </div>\n");
      out.write("    \n");
      out.write("        <!-- 카테고리/제조사별 3개정도? \n");
      out.write("                로얄캐닌/네츄럴코어/ANF-->\n");
      out.write("        <!-- 자견용(퍼피)/성견용(어덜트)/노령견용(시니어)/전연령용\n");
      out.write("                각 DB 5개 정도씩? -->\n");
      out.write("\n");
      out.write("                <div class=\"store_new_products_txt\">\n");
      out.write("                    <h2>* DRY FOOD FOR DOG *</h2>\n");
      out.write("                    <p>From raw materials for dogs to other well-being pet foods</p>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("<div class=\"login_didididiv\">\n");
      out.write("	\n");
      out.write("	<!-- 카테고리 목록 -->\n");
      out.write("	<ul class=\"menu__tabs\">\n");
      out.write("			<li><a class=\"active\" href=\"#item-1\">전체보기</a></li>\n");
      out.write("			<li><a href=\"#item-2\">사료</a></li>	\n");
      out.write("			<li><a href=\"#item-3\">장난감</a></li>	\n");
      out.write("		</ul>\n");
      out.write("		<section class=\"menu__wrapper\">\n");
      out.write("		\n");
      out.write("		\n");
      out.write("		<!-- 전체보기 -->\n");
      out.write("			<article id=\"item-1\" class=\"menu__item item-active\">\n");
      out.write("				\n");
      out.write("				<div class=\"container-fluid\">\n");
      out.write("     <div class=\"row\">\n");
      out.write("      ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("     </div>\n");
      out.write("    </div>\n");
      out.write("				\n");
      out.write("				\n");
      out.write("\n");
      out.write("			</article>\n");
      out.write("			\n");
      out.write("			\n");
      out.write("			<!-- 사료&간식 -->\n");
      out.write("			<article id=\"item-2\" class=\"menu__item\">\n");
      out.write("				\n");
      out.write("				<div class=\"container-fluid\">\n");
      out.write("     <div class=\"row\">\n");
      out.write("      ");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("     </div>\n");
      out.write("    </div>\n");
      out.write("				\n");
      out.write("				\n");
      out.write("			</article>\n");
      out.write("			\n");
      out.write("			\n");
      out.write("			<!-- 용품(장난감) -->\n");
      out.write("			<article id=\"item-3\" class=\"menu__item\">\n");
      out.write("				\n");
      out.write("				<div class=\"container-fluid\">\n");
      out.write("     <div class=\"row\">\n");
      out.write("      ");
      if (_jspx_meth_c_005fforEach_005f2(_jspx_page_context))
        return;
      out.write("\n");
      out.write("     </div>\n");
      out.write("    </div>\n");
      out.write("			</article>\n");
      out.write("\n");
      out.write("\n");
      out.write("		</section>\n");
      out.write("		\n");
      out.write("	\n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("                <!-- 제조사별/연령별 체크박스 -->\n");
      out.write("       ");
      out.write("\n");
      out.write("\n");
      out.write("	<!-- <div class=\"store_wrapper\">\n");
      out.write("			상품 카테고리별 출력 선택 \n");
      out.write("			<h2>카테고리별 출력</h2>\n");
      out.write("			<div style=\"color:fuchsia; display: inline-block;\" >\n");
      out.write("			상품 카테고리(선택)\n");
      out.write("			<select id=\"categoryNumSelect\" name=\"categoryNum\" onchange=\"selectACategory()\">\n");
      out.write("					<option hidden=\"hidden\">전체보기</option>\n");
      out.write("					<option value=\"01\">영양제</option>\n");
      out.write("					<option value=\"02\">간식</option>\n");
      out.write("					<option value=\"03\">사료</option>\n");
      out.write("			</select>\n");
      out.write("			</div>\n");
      out.write("			</div>	 -->		\n");
      out.write("			\n");
      out.write("			\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/1Team/master/team1ShopForDog.jsp(221,6) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("p");
      // /WEB-INF/views/1Team/master/team1ShopForDog.jsp(221,6) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/1Team/master/team1ShopForDog.jsp(221,6) '${products}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${products}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("           <div class=\"col-md-3\">\n");
            out.write("           <a href=\"get.aProductTeam1?product_num=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.product_num}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"><div class=\"thumbnail\">\n");
            out.write("                <img src=\"resources/reviewFile/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.product_thumnail }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" style=\"height: 300px;width:300px\">\n");
            out.write("                <div class=\"caption\">\n");
            out.write("                  <p>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:length(p.product_title)>20?fn:substring(p.product_title,0,20)+=\"...\":p.product_title }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0));
            out.write("</p>\n");
            out.write("                  <p>");
            if (_jspx_meth_fmt_005fformatNumber_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("원</p>\n");
            out.write("                </div>\n");
            out.write("            </div></a>\n");
            out.write("           </div>\n");
            out.write("         ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    boolean _jspx_th_fmt_005fformatNumber_005f0_reused = false;
    try {
      _jspx_th_fmt_005fformatNumber_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatNumber_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/1Team/master/team1ShopForDog.jsp(227,21) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.product_price }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/views/1Team/master/team1ShopForDog.jsp(227,21) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f0.setPattern("#,###");
      int _jspx_eval_fmt_005fformatNumber_005f0 = _jspx_th_fmt_005fformatNumber_005f0.doStartTag();
      if (_jspx_th_fmt_005fformatNumber_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f0);
      _jspx_th_fmt_005fformatNumber_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatNumber_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatNumber_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /WEB-INF/views/1Team/master/team1ShopForDog.jsp(245,6) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("s");
      // /WEB-INF/views/1Team/master/team1ShopForDog.jsp(245,6) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/1Team/master/team1ShopForDog.jsp(245,6) '${foods}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${foods}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("           <div class=\"col-md-3\">\n");
            out.write("           <a href=\"get.aProductTeam1?product_num=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s.product_num}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"><div class=\"thumbnail\">\n");
            out.write("                <img src=\"resources/reviewFile/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s.product_thumnail }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" style=\"height: 300px;width:300px\">\n");
            out.write("                <div class=\"caption\">\n");
            out.write("                  <p>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:length(s.product_title)>20?fn:substring(s.product_title,0,20)+=\"...\":s.product_title }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0));
            out.write("</p>\n");
            out.write("                  <p>");
            if (_jspx_meth_fmt_005fformatNumber_005f1(_jspx_th_c_005fforEach_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
              return true;
            out.write("원</p>\n");
            out.write("                   \n");
            out.write("                </div>\n");
            out.write("            </div></a>\n");
            out.write("           </div>\n");
            out.write("         ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f1 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    boolean _jspx_th_fmt_005fformatNumber_005f1_reused = false;
    try {
      _jspx_th_fmt_005fformatNumber_005f1.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatNumber_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f1);
      // /WEB-INF/views/1Team/master/team1ShopForDog.jsp(251,21) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s.product_price }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/views/1Team/master/team1ShopForDog.jsp(251,21) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f1.setPattern("#,###");
      int _jspx_eval_fmt_005fformatNumber_005f1 = _jspx_th_fmt_005fformatNumber_005f1.doStartTag();
      if (_jspx_th_fmt_005fformatNumber_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f1);
      _jspx_th_fmt_005fformatNumber_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatNumber_005f1, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatNumber_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f2 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f2_reused = false;
    try {
      _jspx_th_c_005fforEach_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f2.setParent(null);
      // /WEB-INF/views/1Team/master/team1ShopForDog.jsp(269,6) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setVar("t");
      // /WEB-INF/views/1Team/master/team1ShopForDog.jsp(269,6) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/1Team/master/team1ShopForDog.jsp(269,6) '${toys}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${toys}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f2 = _jspx_th_c_005fforEach_005f2.doStartTag();
        if (_jspx_eval_c_005fforEach_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("           <div class=\"col-md-3\">\n");
            out.write("           <a href=\"get.aProductTeam1?product_num=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${t.product_num}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"><div class=\"thumbnail\">\n");
            out.write("                <img src=\"resources/reviewFile/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${t.product_thumnail }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" style=\"height: 300px;width:300px\">\n");
            out.write("                <div class=\"caption\">\n");
            out.write("                  <p>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:length(t.product_title)>20?fn:substring(t.product_title,0,20)+=\"...\":t.product_title }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0));
            out.write("</p>\n");
            out.write("                  <p>");
            if (_jspx_meth_fmt_005fformatNumber_005f2(_jspx_th_c_005fforEach_005f2, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f2))
              return true;
            out.write("원</p>\n");
            out.write("                   \n");
            out.write("                </div>\n");
            out.write("            </div></a>\n");
            out.write("           </div>\n");
            out.write("         ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f2.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f2.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f2);
      _jspx_th_c_005fforEach_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f2, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f2)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f2 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    boolean _jspx_th_fmt_005fformatNumber_005f2_reused = false;
    try {
      _jspx_th_fmt_005fformatNumber_005f2.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatNumber_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f2);
      // /WEB-INF/views/1Team/master/team1ShopForDog.jsp(275,21) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f2.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${t.product_price }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/views/1Team/master/team1ShopForDog.jsp(275,21) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f2.setPattern("#,###");
      int _jspx_eval_fmt_005fformatNumber_005f2 = _jspx_th_fmt_005fformatNumber_005f2.doStartTag();
      if (_jspx_th_fmt_005fformatNumber_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f2);
      _jspx_th_fmt_005fformatNumber_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatNumber_005f2, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatNumber_005f2_reused);
    }
    return false;
  }
}
